campost/campost/urls.py
from django.contrib import admin
from django.urls import path,include
from client import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', views.home),
    path('connexion/', views.connexion),
    path('compte/', views.traiter_compte, name = "edite"),
    
    #path('',views.add_show, name = "addandshow"),
    path('client/',views.traiter_client, name = "edit"),
    #path('',views.traiter_compte, name = "edite"),
    path('login/', views.login_user),
    path('deconnexion/', views.deconnexion),
    path('delete/<int:id>/',views.delete_data, name = "deletedata"),
    path('client/show/<int:id>/',views.show_client, name = "show_client"),
    
    
    # Les liens de l'administrateur
    path('super/dashboard',views.admin_dashboard, name = "admin_dashboard"),
    path('super/transactions',views.admin_transactions, name = "admin_dashboard"),
    path('super/parametres/agences',views.admin_parametres_agences, name = "admin_parametres_agences"),
    path('super/parametres/utilisateurs',views.admin_parametres_utilisateurs, name = "admin_parametres_utilisateurs"),
    path('super/clients',views.admin_clients, name = "admin_clients"),
    path('super/client/show/<int:id>',views.admin_client, name = "admin_client"),
    
    #Les liens du Receveur
    path('receveur/dashboard',views.receveur_dashboard, name = "receveur_dashboard"),
    path('receveur/utilisateurs',views.receveur_utilisateurs, name = "receveur_parametres_utilisateurs"),
    path('receveur/transactions',views.receveur_transactions, name = "receveur_transactions"),
    #path('receveur/transactions',views.receveur_transactions, name = "receveur_dashboard"),
    
    #Les liens de l'agent
    path('agent/dashboard',views.agent_dashboard, name = "agent_dashboard"),
    path('agent/transactions',views.agent_transactions, name = "agent_transactions"),
    path('agent/client/create',views.agent_create_client, name = "agent_create_client"),
    path('agent/client/search',views.agent_client, name = "agent_client"),
    path('agent/depot',views.agent_depot, name = "agent_depot"),
    path('agent/retrait',views.agent_retrait, name = "agent_retrait"),
]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

campost/client/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#class User(models.Model):
 #   name =  models.CharField(max_length=70)
 #  telephone =  models.CharField(max_length=100)
 #   email =  models.CharField(max_length=100)
 #   password =  models.CharField(max_length=100)
    


class Role(models.Model):
    nom = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return "{}".format(self.nom)

class Region(models.Model):
    nom = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
     
    def __str__(self) -> str:
        return "{}".format(self.nom)    
    
class Agence(models.Model):
    region = models.ForeignKey(Region, null=True, on_delete=models.SET_NULL)
    nom = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return "{}".format(self.nom)
           

class Profil(models.Model):
    user = models.OneToOneField(User,null=True, on_delete=models.SET_NULL)  # La liaison OneToOne vers le modèle User
    role = models.ForeignKey(Role, null=True, on_delete=models.SET_NULL)  # La liaison OneToOne vers le modèle Role
    agence = models.ForeignKey(Agence, null=True, on_delete=models.SET_NULL)
    avatar = models.ImageField(null=True, blank=True, upload_to="avatars/")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    connected_at = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return "Profil de {0}".format(self.user.username) 
    
class Client(models.Model):
    nom = models.CharField(max_length=70)
    prenom = models.CharField(max_length=70)
    telephone = models.IntegerField(max_length=70)
    adresse = models.CharField(max_length=200)
    dtn=models.DateField(blank=True)
    lieu = models.CharField(max_length=200,blank=True, null=True)
    photo = models.ImageField(null=True, blank=True, upload_to="photos/")
    created_at = models.DateTimeField(auto_now_add=True,blank=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True)
    agence = models.ForeignKey(Agence, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    
    def __str__(self) -> str:
        return "{} {}".format(self.nom,self.prenom)
    
class Compte(models.Model):
    client = models.OneToOneField(Client,null=True, on_delete=models.SET_NULL)
    numero = models.CharField(max_length=100)
    solde = models.FloatField(default=0,verbose_name=u"Solde initial du compte")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return "{}".format(self.numero)
        
    
class Operation(models.Model):
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL)
    compte = models.ForeignKey(Compte, null=True, on_delete=models.SET_NULL)
    montant =models.IntegerField(default=0)
    autorisation = models.CharField(max_length=100)
    is_deposit=models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    region = models.ForeignKey(Region, null=True, on_delete=models.SET_NULL)
    agence = models.ForeignKey(Agence, null=True, on_delete=models.SET_NULL)          


   
   
     

campost/client/views.py
from django.shortcuts import render,HttpResponseRedirect, redirect
from django.contrib.auth.models import User
from .forms import  ClientStore, CompteGestion,Login, AgenceForm,UtlisateurForm,ClientSearch,TransactionForm
from .models import  Client, Compte, Agence, Role, Region,Operation,Profil
from django.http import HttpResponse
from django.contrib.auth import authenticate, login,logout
from django.urls import reverse
import datetime

#ClientRegistration,
#User,
# Create your views here.
#def add_show(request):
    #if request.method == 'POST':
       #fm = ClientRegistration(request.POST)
        #if fm.is_valid():
            #nm = fm.cleaned_data['name']
            #tl = fm.cleaned_data['telephone']
            #em = fm.cleaned_data['email']
            #pw = fm.cleaned_data['password']
            #reg = User(name = nm, telephone = tl, email = em, password = pw)
            #reg.save()
            #fm = ClientRegistration()
    #else:
        #fm = ClientRegistration()
    #return render(request, 'client/addandshow.html',{'form':fm})
#cette fonction permet d'ajouteret d'afficher les infos d'un client

def home(request):
        return render(request, 'home.html')
    
    
def connexion(request):
        return render(request, 'connexion.html')   


    
#def comptes_view(request):
 #   return HttpResponse('LES COMPTES')



def traiter_client(request):
    if request.method == 'POST':
        fm = ClientStore(request.POST)
        if fm.is_valid():
            nom = fm.cleaned_data['nom']
            pren = fm.cleaned_data['prenom']
            tel = fm.cleaned_data['telephone']
            adr = fm.cleaned_data['adresse']
            reg = Client(nom = nom, prenom = pren, telephone =tel , adresse = adr)
            reg.save()
            fm = ClientStore()
    else:
        fm = ClientStore()
    clien = Client.objects.all()
    return render(request, 'Clients/edit.html',{'form':fm, 'cli':clien})

#cette fonction permet de supprimer les donnes
def delete_data(request, id):
    if request.method == 'POST':
        pi = Client.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/')
    
#cette fonction permet de supprimer les donnes
def show_client(request, id):
   # if request.method == 'POST':
    pi = Client.objects.get(pk=id)
       # pi.delete()
    return render(request, 'Clients/show.html',{'client':pi})   
    

def traiter_compte(request):
    if request.method == 'POST':
        fm = CompteGestion(request.POST)
        if fm.is_valid():
            num = fm.cleaned_data['numero de compte']
            cli = fm.cleaned_data['client']
            solde = fm.cleaned_data['solde']
            jr = fm.cleaned_data['date ouverture']
            cpt = Compte(numero_de_compte = num, client = cli, solde =solde , date_ouverture = jr)
            cpt.save()
            fm = CompteGestion()
    else:
        fm = CompteGestion()
    compt = Compte.objects.all()
    return render(request, 'Comptes/edite.html',{'form':fm, 'cpt':compt})

#cette fonction permet de supprimer les donnes
def delete_data(request, id):
    if request.method == 'POST':
        pi = Compte.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/')
    
def login_user(request):
    error = False
    if request.method == "POST":
        form = Login(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                now = datetime.datetime.now()
                user.profil.connected_at = now
                user.profil.save()
                login(request, user)  # nous connectons l'utilisateur
                if user.profil.role.id==1:
                    return redirect('/super/dashboard')
                if user.profil.role.id==2:
                    return redirect('/receveur/dashboard')
                if user.profil.role.id==3:
                    return redirect('/agent/dashboard')
                
            else: # sinon une erreur sera affichée
                error = True
    else:
        form = Login()

    return render(request, 'Profil/login.html', locals()) 

def deconnexion(request):
    logout(request)
    return redirect(reverse(login_user))


# Les actions de l'admin

def admin_dashboard(request):
    #return redirect('/some/url/')
    user = current_user = request.user
    if current_user.profil.role.id==1:
        return render(request, 'Admin/dashboard.html',locals())
    else:    
        return redirect('/login')
    
def admin_parametres_agences(request):
    #return redirect('/some/url/')
    if request.method=='POST':
        form = AgenceForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data["nom"]
            region = form.cleaned_data["region"]
            agence = Agence(nom=nom,region=region)
            agence.save()
            return HttpResponseRedirect(request.path_info)   
    else:    
        current_user = request.user
        if current_user.profil.role.id==1:
            agences = Agence.objects.all()
            regions = Region.objects.all()
            form = AgenceForm()
            return render(request, 'Admin/Agences/index.html',{'agences':agences,'regions':regions,'form':form})
        else:    
            return redirect('/login')
    

#Je gere les comptes utilisateurs ici
def admin_parametres_utilisateurs(request):
    #return redirect('/some/url/')
    if request.method=='POST':
        form = UtlisateurForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            ag_id = form.data.get("agence")
            role_id = form.data.get("role")
            agence = Agence.objects.get(pk=ag_id)
            role = Role.objects.get(pk=role_id)
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            utilisateur = User.objects.create_user(username, email, password)
            profil = Profil(user=utilisateur,role=role,agence=agence)
            profil.save()
            return HttpResponseRedirect(request.path_info)   
    else:    
        current_user = request.user
        if current_user.profil.role.id==1:
            utilisateurs = Profil.objects.all()
            agences = Agence.objects.all()
            roles = Role.objects.all()
            #form = Form()
            return render(request, 'Admin/Utilisateurs/index.html',{'agences':agences,'utilisateurs':utilisateurs,'roles':roles})
        else:    
            return redirect('/login')
    
#Je gere les comptes utilisateurs ici
def admin_clients(request):
    #return redirect('/some/url/')
    
    current_user = request.user
    if current_user.profil.role.id==1:
        clients = Client.objects.all()
        #form = Form()
        return render(request, 'Admin/Clients/index.html',{'clients':clients,})
    else:    
        return redirect('/login')
#Je gere les comptes utilisateurs ici
def admin_client(request,id):
    #return redirect('/some/url/')
    
    current_user = request.user
    if current_user.profil.role.id==1:
        client = Client.objects.get(pk=id)
        #form = Form()
        return render(request, 'Admin/Clients/show.html',{'client':client})
    else:    
        return redirect('/login')     
    
def admin_transactions(request):
    #return redirect('/some/url/')
    user = current_user = request.user
    if current_user.profil.role.id==1:
        transactions = Operation.objects.all()
        return render(request, 'Admin/transactions.html',{'transactions':transactions})
    else:    
        return redirect('/login')
    


#Liste des actions du receveur
#Je gere les comptes utilisateurs ici
def receveur_utilisateurs(request):
       
    current_user = request.user
    if current_user.profil.role.id==2:
        agence = current_user.profil.agence
        utilisateurs = Profil.objects.filter(agence=agence)
        return render(request, 'Receveur/Utilisateurs/index.html',{'utilisateurs':utilisateurs})
    else:    
        return redirect('/login')
    
def receveur_dashboard(request):
    current_user = request.user
    if current_user.profil.role.id==2:
        return render(request, 'Receveur/dashboard.html',locals())
    else:    
        return redirect('/login')
    
def receveur_transactions(request):
    current_user = request.user
    if current_user.profil.role.id==2:
        transactions = Operation.objects.filter(agence=current_user.profil.agence)
        return render(request, 'Receveur/transactions.html',{'transactions':transactions})
    else:    
        return redirect('/login') 

def agent_dashboard(request):
    current_user = request.user
    if current_user.profil.role.id==3:
        return render(request, 'Agent/dashboard.html',locals())
    else:    
        return redirect('/login')
    
def agent_transactions(request):
    current_user = request.user
    if current_user.profil.role.id==3:
        transactions = Operation.objects.filter(user=current_user)
        return render(request, 'Agent/transactions.html',{'transactions':transactions})
    else:    
        return redirect('/login')    
 
def agent_create_client(request):
    #return redirect('/some/url/')
    if request.method=='POST':
        form = ClientStore(request.POST, request.FILES)
        if form.is_valid():
            nom = form.cleaned_data["nom"]
            prenom = form.cleaned_data["prenom"]
            telephone = form.cleaned_data["telephone"]
            adresse = form.cleaned_data["adresse"]
            dtn = form.data.get("dtn")
            lieu = form.data.get("lieu")
            photo = form.data.get("photo")
            current_user = request.user
            agence = current_user.profil.agence
            now = datetime.datetime.now()

campost/client/templates/Clients/app.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion  des Clients</title>
    <link rel="stylesheet" href=" {% static 'assets/css/bootstrap.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Gestion de la Base Clients</h2>
        {% block content%}  {% endblock content%}
    </div>
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/popper.js' %}"></script> 
</body>
</html>

campost/client/templates/Clients/client.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GESTION CLIENTS</title>
    <link rel="stylesheet" href=" {% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href=" {% static 'assets/css/adminlte.css' %}">
    <link rel="stylesheet" href=" {% static 'assets/css/style.css' %}">
</head>
<body>
    <div class="container mt-5">
        {% block header%}  {% endblock header%}
        {% block content%}  {% endblock content%}
    </div>
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.js' %}"></script> 
   

<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
    $('.data-table').DataTable({
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
</script>
</body>
</html>

campost/client/templates/Clients/edit.html
{% extends 'Clients/client.html' %}
{% block content %}
<div class="row">
    <div class="col-md-4 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h4 class="text-center alert alert alert-info ">Ajouter un nouveau client </h4>
          <form action="" method="POST">
              {%csrf_token %}
              {{form.as_p}}
              <input type="submit" class="btn btn-success" value="Ajouter">
          </form>
        </div>  
      </div>    
    </div>
    <div class="col-md-8 col-sm-12">
        <div class="card">
          <div class="card-header"><h4 class="text-center">LISTE DES CLIENTS</h4></div>
          <div class="card-body">
            <div class="table-responsive">
              
        {% if cli %}
        <table class="table table-hover table-bordered table-sm table-striped data-table">
            <thead>
              <tr>
                
                <th scope="col">Nom</th>
                <th scope="col">Telephone</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
                {% for st in cli %}
                  <tr>
                    <td><a href="/client/show/{{st.id}}" class="">{{st.nom}} {{st.prenom}}</a></td>
                    <td>{{st.telephone}}</td>
                    <td>
                      <div class="dropdown">
                        <button class="btn link-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <ul class="list-unstyled">
                            <li class="p-1">
                              <a href="/client/update/{{st.id}}" class="">Modifier</a>
                            </li>  
                            <li class="p-1">
                              <a href="/client/suspend/{{st.id}}" class="">Suspendre</a>
                            </li>  
                          </ul>
                        </div>
                      </div>
                        
                        
                    </td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
            {% else %}
            <h4 class="text-center alert alert-warning">Pas d'enregistrement</h4>
            {% endif %}
            </div>  
          </div>  
        </div>  
    </div>
</div>
{% endblock content %}

campost/client/templates/Clients/show.html
{% extends 'Clients/client.html' %}
{% block header %}
<h2 class="text-center bg-light">{{ client }}</h2>
  <div class="bg-info p-2 mb-2"><a href="/client">Retourner a la liste des client</a></div>
{% endblock header %}
{% block content %}
<div class="row">
    <div class="col-md-4 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h4 class="text-center alert alert alert-info ">{{ client }} </h4>
          <p>NOM : <span class="text-bold">{{ client.nom }}</span></p>
          <p>PRENOM : <span class="text-bold">{{ client.prenom }}</span></p>
          <p>TELEPHONE : <span class="text-bold">{{ client.telephone }}</span></p>
          <p>ADRESSE PHYSIQUE : <span class="text-bold">{{ client.adresse }}</span></p>
          <p>DATE DE NAISSANCE : <span class="text-bold">{{client.dtn|date:"d-m-Y" }}</span></p>
        </div>  
      </div>    
    </div>
    <div class="col-md-8 col-sm-12">
        <div class="card">
          <div class="card-header"><h4 class="text-center">HISTORIQUE DES TRANSACTIONS</h4></div>
          <div class="card-body">
            <div class="table-responsive">
              
        {% if True %}
        <table class="table table-hover table-bordered table-sm table-striped data-table">
            <thead>
              <tr>
                
                <th scope="col">NUMERO DE COMPTE</th>
                <th> SOLDE </th>
              </tr>
            </thead>
            <tbody>
                {% for compte in client.compte_set.all %}
                  <tr>
                    <td><a href="/client/compte/show/{{st.id}}" class="">{{compte.numero}}</a></td>
                    <td>{{compte.solde}}</td>
                    
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
            {% else %}
            <h4 class="text-center alert alert-warning">AUCUNE OPERATION</h4>
            {% endif %}
            </div>  
          </div>  
        </div>  
    </div>
</div>
{% endblock content %}